[package]
name = "ownership"
version = "0.1.0"
authors = ["TheAdnan <adnankicin92@gmail.com>"]

[dependencies]

# cargo run --bin main
[[bin]]
name="main"
path="src/main.rs"

# cargo run --bin ownership
[[bin]]
name="ownership"
path="src/ownership.rs"
